spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: 
    url: jdbc:mysql://localhost:3306/quintrix
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8080
<<<<<<< HEAD
=======
  
cloud:
  aws:
    credentials:
      access-key: 
      
  cloud:
   aws:
      credentials:
      secret-key: 
         
   cloud:
      aws:
       region:
       static: us-east-1
         
      cloud:
        aws:
         stack:
         auto: false

spring:
  servlet:
     multipart:
     max-file-size: 100MB

  spring:
    servlet:
      multipart:
      max-request-size: 100MB



>>>>>>> origin/develop
