spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: 
    url: jdbc:mysql://localhost:3306/quintrix
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8080