spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: 
    url: jdbc:mysql://carservice.czibfhut1usj.us-east-2.rds.amazonaws.com/cars
    username: quintrix_cars
    password: xtUVF6Yf685RhGJ5
    
  servlet:
    multipart:
    max-file-size: 100MB
    max-request-size: 100MB

server:
    port: 8080

previousOwnerSerivce:
    getUrl: http://localhost:8080/customers
    name: root
    password: toor
  
cloud:
  aws:
    credentials:
       access-key: 
       secret-key: 
    region:
       static: us-east-1
       use-default-aws-region-chain: true
         
    stack:
       auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error 

application:
  finance-length: 36


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
        
resilience4j:
  circuitbreaker:
    instances:
      searchCars:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
          

  
agentService:
  getUrl: https://gorest.co.in/public/v2/users     


