spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: 
    url: jdbc:mysql://localhost:3306/quintrix
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 8080
  
cloud:
  aws:
    credentials:
       access-key: 
       secret-key: 
    region:
       static: us-east-1
       use-default-aws-region-chain: true
         
    stack:
       auto: false

  spring:
   servlet:
     multipart:
     max-file-size: 100MB
     max-request-size: 100MB